20231129/photoproject/photo/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = "photo"

# URLパターンを登録する変数
urlpatterns = [
    # photoアプリへのアクセスはviewsモジュールのIndexViewを実行
    path("",views.IndexView.as_view(),name="index"),

    # 写真投稿ページへのアクセスはviewsモジュールのCreatePhotoViewを実行
    path("post/",views.CreatePhotoView.as_view(),name="post"),

    # 投稿完了ページへのアクセスはviewsモジュールのPostSucessViewを実行
    path("post_done/",views.PostSuccessView.as_view(),name="post_done"),

    # カテゴリ一覧ページ
    # photos/<Categorysテーブルのid値>にマッチング
    # <int:category>は辞書{category:id値(int)}としてCategoryViewに渡される
    path("photos/<int:category>/",views.CategoryView.as_view(),name="photos_cat"),

    # ユーザの投稿一覧ページ
    # photos/<ユーザテーブルのid値>にマッチング
    # <int:user>は辞書{user:id値(int)}としてUserViewに渡される
    path("user-list/<int:user>/",views.UserView.as_view(),name="user_list"),

    # 詳細ページ
    # photo-detail/<Photo postsテーブルのid値>にマッチング
    # <int:pk>は辞書{pk:id値(int)}としてDetailViewに渡される
    path("photo-detail/<int:pk>/",views.DetailView.as_view(),name="photo_detail"),

    # マイページ
    # mypage-へのアクセスはMypageViewを実行
    path("mypage/",views.MypageView.as_view(),name="mypage"),

    # 投稿写真の削除
    # photo/<Photo postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk:id値(int)}としてDeleteViewに渡される
    path("photo/<int:pk>/delete/",views.PhotoDeleteView.as_view(),name="photo_delete"),
]

20231129/photoproject/photo/templates/photo/detail.html
<!-- ベーステンプレートを適用する-->
{%extends "base.html"%}

<!-- ヘッダー情報のページタイトルを設定する-->
{%block title%}Photo Detail{%endblock%}

{%block contents%}

<!-- Bootstrapのグリッドシステム-->
<br>
<div class="container">
    <!-- 行を配置-->
    <div class="row">
        <!-- 列の左右に余白offset-3を入れる-->
        <div class="col offset-3">
            <!-- タイトル-->
            <h2>{{object.title}}</h2>
            <!-- コメント-->
            <p>{{object.comment}}</p>
            <br>
            <!-- 投稿日時-->
            <p>{{object.posted_at}}に投稿</p>
            <!-- 1枚目の写真-->
            <p><img src="{{object.image1.url}}" alt=""></p>
            <!-- 2枚目の写真ｇ投稿されていたら表示する-->
            {%if object.image2%}
            <p><img src="{{object.image2.url}}" alt="">
            </p>
            {%endif%}

            <!-- 投稿写真がログイン中のユーザのものであれば削除ボタンを表示-->
            {%if request.user == object.user%}
            <form method="post" action="">
                <!-- リンク先のURL: photo/<Photo postsテーブルのid値>/delete/-->
                <a class="btn btn-primary my-2" href="{%url 'photo:photo_delete' object.pk%}">削除する</a>
            </form>
            {%endif%}
        </div>
    </div>
</div>
{%endblock%}

20231129/photoproject/photo/templates/photo/index.html
<!-- ベーステンプレートを適用する-->
{%extends "base.html"%}

<!-- ヘッダー情報のページタイトルを設定する-->
{%block title%}Photo Gallery{%endblock%}

{%block contents%}

<!-- タイトルテンプレートの組み込み-->
{%include "photo/photos_title.html"%}

<!-- 投稿一覧テンプレートの組み込み-->
{%include "photo/photos_list.html"%}

<!-- ページネーションの組み込み-->
{%include "pagination.html"%}

{%endblock%}

20231129/photoproject/photo/templates/photo/mapage.html
<!-- ベーステンプレートを適用する-->
{%extends "base.html"%}

<!-- ヘッダー情報のページタイトルを設定する-->
{%block title%}Mypage{%endblock%}

{%block contents%}

<!-- タイトルテンプレートは組み込まない-->

<!-- ユーザの投稿件数を表示-->
{%if user.is_authenticated%}
<br>
<div class="" style="text-align: center;">
    <h4>{{user.username}}さんのマイページ</h4>
    {%if object_list.count == 0%}
    <p>{{user.username}}さんの投稿はありません。</p>
    {%else%}
    <p>投稿<strong>{{object_list.count}}</strong>件</p>
    {%endif%}
    <a href="{%url 'photo:post'%}">投稿する</a>
</div>
{%endif%}

<!-- 投稿一覧テンプレートの組み込み-->
{%include "photo/photos_list.html"%}

<!-- ページネーションの組み込み-->
{%include "pagination.html"%}

{%endblock%}

20231129/photoproject/photo/templates/photo/photo_delete.html
<!-- ベーステンプレートを適用する-->
{%extends "base.html"%}

<!-- ヘッダー情報のページタイトルを設定する-->
{%block title%}Photo Detail{%endblock%}

{%block contents%}

<!-- Bootstrapのグリッドシステム-->
<br>
<div class="container">
    <!-- 行を配置-->
    <div class="row">
        <!-- 列の左右に余白offset-3を入れる-->
        <div class="col offset-3">
            <form method="post" action="">
                <br>
                <p>削除してもいいですか？</p>
                {%csrf_token%}
                <button class="btn btn-primary my-2" type="submit">削除</button>
                <a class="btn btn-secondary my-2" href="{%url 'photo:photo_detail' object.pk%}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{%endblock%}

20231129/photoproject/photo/templates/photo/photos_list.html
<!-- ここまで削除-->

<!-- <div class="album py-5 bg-light">から4個連続の</div>まで残す-->

  <div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用-->
    <div class="container">
      <!-- 行要素を配置-->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- レコードが格納されたobjet_listからレコードを1行ずつrecordに取り出す-->
        {%for record in object_list%}
        <!-- 列要素を配置-->
        <div class="col">
          <div class="card shadow-sm">
            <!-- svgタグをimgに変更　src属性を追加して1枚目のイメージのURLを設定-->
            <img src="{{record.image1.url}}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/>
            <!-- <text>～</text>を削除-->
            <!-- タイトルとボタンを出力するブロック-->
            <div class="card-body">
              <p class="card-text">
                <!-- titleフィールドを出力-->
                {{record.title}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{%url 'photo:photo_detail' record.pk%}'">View</button>
                  <!-- カテゴリを表示するボタン-->
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{%url 'photo:photos_cat' category=record.category.id%}'">{{record.category.title}}</button>
                </div>
                <!-- 投稿したユーザ名を出力-->
                <a href="{%url 'photo:user_list' user=record.user.id%}">
                  <small class="text-muted">{{record.user.username}}</small>
                </a>
              </div>
            </div>
          </div>
          <!-- 列要素ここまで-->
        </div>
        <!-- forブロック終了-->
        {%endfor%}
        <!-- 行要素ここまで-->
        <!-- 8個の<div class="col">～</div>のブロックを削除-->
      
      <!-- 3個連続の</div>を残してドキュメントの末尾まで削除-->
      </div>
      <!-- グリッドシステムここまで-->
    </div>
  </div>

20231129/photoproject/photo/templates/photo/photos_title.html
<!-- ここまでのコードをすべて削除-->

<!-- タイトルとナビゲーションボタン-->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文-->
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-muted">コメントを見て写真に描かれた世界に思いを馳せましょう。<br>素敵な写真とコメントをお待ちしています！</p>
        <p>
          <!-- ナビゲーションボタン-->
          {%if user.is_authenticated%}
          
          <!-- ログイン中のボタン-->
          <a class="btn btn-primary my-2" href="{%url 'photo:post'%}">投稿する</a>
          <a class="btn btn-secondary my-2" href="{%url 'accounts:logout'%}">ログアウト</a>
          {%else%}

          <!-- ログイン状態でない場合のボタン-->
          <a href="{%url 'accounts:signup'%}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{%url 'accounts:login'%}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {%endif%}
        </p>
      </div>
    </div>
  </section>

  <!-- 以下のコードをすべて削除-->

20231129/photoproject/photo/templates/photo/post_photo.html
<!-- ベーステンプレートを適用する-->
{%extends "base.html"%}

<!-- ヘッダー情報のページタイトルを設定する-->
{%block title%}Post{%endblock%}

{%block contents%}

<!-- Bootstrapのグリッドシステム-->
<br>
<div class="container">

    <!-- 行を配置-->
    <div class="row">

        <!-- 列の左右に余白offset-2を入れる-->
        <div class="col offset-2">

            <!-- ファイルをアップロードする場合はenctype="multipart/form-data"が必要-->
            <form method="post" action="" enctype="multipart/form-data">
                {%csrf_token%}
                <table>
                    <tr><th>カテゴリ</th><td>{{form.category}}</td></tr>
                    <tr><th>タイトル</th><td>{{form.title}}</td></tr>
                    <tr><th>コメント</th><td>{{form.comment}}</td></tr>
                    <tr><th>画像1</th><td>{{form.image1}}</td></tr>
                    <tr><th>画像2</th><td>{{form.image2}}</td></tr>
                </table>
                <hr>
                <button type="submit">投稿する</button>
            </form>
        </div>
    </div>
</div>
{%endblock%}

20231129/photoproject/photo/templates/photo/post_success.html
<!-- ベーステンプレートを適用する-->
{%extends "base.html"%}

<!-- ヘッダー情報のページタイトルを設定する-->
{%block title%}Post Success{%endblock%}

{%block contents%}

<!-- Boostrapのグリッドシステム-->
<br><br>
<div class="container">

    <!-- 行を配置-->
    <div class="row">

        <!-- 列の左右に余白offset-2を入れる-->
        <div class="col offset-2">
            <h4>投稿が完了しました！</h4>
        </div>
    </div>
</div>
{%endblock%}