Django4ハンドブックsample/sample/chap06/blogproject/blogapp/urls.py
from django.urls import path
from . import views

# URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = 'blogapp'

# URLパターンを登録するためのリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスが''(無し)の場合
    # viewsモジュールのIndexVieを実行
    # URLパターン名は'index'
    path('', views.IndexView.as_view(), name='index'),
    
    # リクエストされたURLが「blog-detal/レコードのid/」の場合
    # viewsモジュールのBlogDetalを実行
    # URLパターン名は'blog_detail'
    path(
        # 詳細ページのURLは「blog-detail/レコードのid/」
        'blog-detail/<int:pk>/',
        # viewsモジュールのBlogDetailを実行
        views.BlogDetail.as_view(),
        # URLパターンの名前を'blog_detail'にする
        name='blog_detail'
        ),
    # scienceカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「science-list/」
        'science-list/',
        # viewsモジュールのBlogDetailを実行
        views.ScienceView.as_view(),
        # URLパターンの名前を'science_list'にする
        name='science_list'
        ),
    # dailylifeカテゴリの一覧ページのURLパターン
    path(
        # dailylifeカテゴリの一覧ページのURLは「dailylife-list/」
        'dailylife-list/',
        # viewsモジュールのDailylifeViewを実行
        views.DailylifeView.as_view(),
        # URLパターンの名前を'dailylife_list'にする
        name='dailylife_list'
        ),
    # musicカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「music-list/」
        'music-list/',
        # viewsモジュールのMusicViewを実行
        views.MusicView.as_view(),
        # URLパターンの名前を'music_list'にする
        name='music_list'
        ),
    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        'contact/',
        # viewsモジュールのInquiryViewを実行
        views.ContactView.as_view(),
        # URLパターンの名前を'contact'にする
        name='contact'
        ),
]

Django4ハンドブックsample/sample/chap06/blogproject/blogproject/urls.py
from django.contrib import admin
 # include()関数を使うためincludeを追加
from django.urls import path, include

# プロジェクトのURLパターンを登録するリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスがadmin/にマッチングした場合
    # admin.site.urlsを呼び出し、Django管理サイトを表示する
    path('admin/', admin.site.urls),
    
    # http(s)://ホスト名/へのアクセスはbbogappの
    # URLConf(urls.py)を呼び出す
    path('', include('blogapp.urls')),
]

Django4ハンドブックsample/sample/chap06/blogproject/blogapp/models.py
from django.db import models

class BlogPost(models.Model):
    '''モデルクラス
    '''
    # カテゴリに設定する項目を入れ子のタプルとして定義
    # タプルの第1要素はモデルが使用する値、
    # 第2要素は管理サイトの選択メニューに表示する文字列
    CATEGORY = (('science', '科学のこと'),
                ('dailylife', '日常のこと'),
                ('music', '音楽のこと'))

    # タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル', # フィールドのタイトル
        max_length=200        # 最大文字数は200
        )
    # 本文用のフィールド
    content = models.TextField(
        verbose_name='本文'   # フィールドのタイトル
        )
    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時', # フィールドのタイトル
        auto_now_add=True       # 日時を自動追加
        )
    # カテゴリのフィールド
    category = models.CharField(
        verbose_name='カテゴリ', # フィールドのタイトル
        max_length=50,        # 最大文字数は50
        choices=CATEGORY # categoryフィールドにはCATEGORYの要素のみを登録
        )
    
    def __str__(self):
        '''Django管理サイトでデータを表示する際に識別名として
           投稿記事のタイトル(titleフィールドの値を表示するために必要
        
        Returns(str):投稿記事のタイトル
        '''
        return self.title
    

Django4ハンドブックsample/sample/chap06/blogproject/blogapp/forms.py
# django.formsをインポート
from django import forms

class ContactForm(forms.Form):
    # フォームのフィールドをクラス変数として定義
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        '''ContactFormのコンストラクター
        
           フィールドの初期化を行う
        '''
        super().__init__(*args, **kwargs)
        # nameフィールドのplaceholderにメッセージを登録
        self.fields['name'].widget.attrs['placeholder'] = \
          'お名前を入力してください'
        # nameフィールドを出力する<input>タグのclass属性を設定
        self.fields['name'].widget.attrs['class'] = 'form-control'
        
        # emailフィールドのplaceholderにメッセージを登録
        self.fields['email'].widget.attrs['placeholder'] = \
          'メールアドレスを入力してください'
        # emailフィールドを出力する<input>タグのclass属性を設定
        self.fields['email'].widget.attrs['class'] = 'form-control'
        
        # titleフィールドのplaceholderにメッセージを登録
        self.fields['title'].widget.attrs['placeholder'] = \
          'タイトルを入力してください'
        # titleフィールドを出力する<input>タグのclass属性を設定
        self.fields['title'].widget.attrs['class'] = 'form-control'
        
        # messageフィールドのplaceholderにメッセージを登録
        self.fields['message'].widget.attrs['placeholder'] = \
          'メッセージを入力してください'
        # messageフィールドを出力する<input>タグのclass属性を設定
        self.fields['message'].widget.attrs['class'] = 'form-control'

Django4ハンドブックsample/sample/chap06/blogproject/blogapp/views.py
from django.shortcuts import render
# django.views.genericからListView、DetailViewをインポート
from django.views.generic import ListView, DetailView
# モデルBlogPostをインポート
from .models import BlogPost
# django.views.genericからFormViewをインポート
from django.views.generic import FormView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからContactFormをインポート
from .forms import ContactForm
# django.contribからmesseagesをインポート
from django.contrib import messages
# django.core.mailモジュールからEmailMessageをインポート
from django.core.mail import EmailMessage

class IndexView(ListView):
    '''トップページのビュー
    
    投稿記事を一覧表示するのでListViewを継承する
    
    Attributes:
      template_name: レンダリングするテンプレート
      context_object_name: object_listキーの別名を設定
      queryset: データベースのクエリ
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # object_listキーの別名を設定
    context_object_name = 'orderby_records'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # BlogPostのレコードを投稿日時の降順で並べ替える
    queryset = BlogPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数を設定
    paginate_by = 4

class BlogDetail(DetailView):
    '''詳細ページのビュー
    
    投稿記事の詳細を表示するのでDetailViewを継承する
     Attributes:
      template_name: レンダリングするテンプレート
      Model: モデルのクラス
    '''
    # post.htmlをレンダリングする
    template_name ='post.html'
    # クラス変数modelにモデルBlogPostを設定
    model = BlogPost

class ScienceView(ListView):
    '''科学(science)カテゴリの記事を一覧表示するビュー
    
    '''
    # science_list.htmlをレンダリングする
    template_name ='science_list.html'
    # クラス変数modelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'science_records'
    # category='science'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='science').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class DailylifeView(ListView):
    '''日常(dailylife)カテゴリの記事を一覧表示するビュー
    
    '''
    # dailylife_list.htmlをレンダリングする
    template_name ='dailylife_list.html'
    # クラス変数modelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'dailylife_records'
    # category='dailylife'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='dailylife').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class MusicView(ListView):
    '''音楽(music)カテゴリの記事を一覧表示するビュー
    
    '''
    # music_list.htmlをレンダリングする
    template_name ='music_list.html'
    # クラス変数modelにモデルBlogPostを設定
    model = BlogPost
    # object_listキーの別名を設定
    context_object_name = 'music_records'
    # category='music'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = BlogPost.objects.filter(
        category='music').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2

class ContactView(FormView):
    '''問い合わせページを表示するビュー
    
    フォームで入力されたデータを取得し、メールの作成と送信を行う
    '''
    # contact.htmlをレンダリングする
    template_name ='contact.html'
    # クラス変数form_classにforms.pyで定義したContactFormを設定
    form_class = ContactForm
    # 送信完了後にリダイレクトするページ
    success_url = reverse_lazy('blogapp:contact')
      
    def form_valid(self, form):
        '''FormViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したデータがPOSTされたときに呼ばれる
        メール送信を行う
        
        parameters:
          form(object): ContactFormのオブジェクト
        Return:
          HttpResponseRedirectのオブジェクト
          オブジェクトをインスタンスかするとsuccess_urlで
          設定されているURLにリダイレクトされる
        '''
        # フォームに入力されたデータをフィールド名を指定して取得
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        # メールのタイトルの書式を設定
        subject = 'お問い合わせ: {}'.format(title)
        # フォームの入力データの書式を設定
        message = \
          '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\n{3}' \
          .format(name, email, title, message)
        # メールの送信元のアドレス(Gmail)
        from_email = 'toshiyakinjo@gmail.com'
        # 送信先のメールアドレス(Gmail)
        to_list = ['toshiyakinjo@gmail.com']
        # EmailMessageオブジェクトを生成
        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        # EmailMessageクラスのsend()でメールサーバーからメールを送信
        message.send()
        # 送信完了後に表示するメッセージ
        messages.success(
          self.request, 'お問い合わせは正常に送信されました。')
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

Django4ハンドブックsample/sample/chap06/blogproject/blogapp/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!DOCTYPE html>
<!-- 言語指定をjaに設定 -->
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- ページタイトル -->
        <title>{% block title %}{% endblock %}</title>
        <!-- ページタイトル横に表示されるアイコン -->
        <!-- staticでfavicon.icoのURLを生成する -->
        <link rel="icon" type="image/x-icon"
  　　　　       href={% static 'assets/favicon.ico' %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
                crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
              rel="stylesheet"
              type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
              rel="stylesheet"
              type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <!-- staticでstyles.cssのURLを生成する -->
        <link href={% static 'css/styles.css' %}
              rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light"
             id="mainNav">
            <div class="container px-4 px-lg-5">
                <!-- 
                ナビゲーションバー左上のアンカーテキストとhref属性の値を設定
                -->
                <a class="navbar-brand"
                   href={% url 'blogapp:index' %}>Django's Blog</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarResponsive"
                        aria-controls="navbarResponsive"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse"
                     id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニュー「HOME」のhrefの値を設定
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'blogapp:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「SCIENCE」のリンク先を
                            名前付きURLパターンscience_listに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'blogapp:science_list' %}">
                               SCIENCE</a>
                        </li>
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「DAILYLIFFE」のリンク先を
                            名前付きURLパターンdailylife_listに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'blogapp:dailylife_list' %}">
                               DAILYLIFFE</a>
                        </li>
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「MUSIC」のリンク先を
                            名前付きURLパターンmusic_listに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'blogapp:music_list' %}">
                               MUSIC</a>
                        </li>
                        <li class="nav-item">
                            <!--
                            ナビゲーションメニューの「CONTACT」のリンク先を
                            名前付きURLパターンcontactに設定する
                            -->
                            <a class="nav-link px-lg-3 py-3 py-lg-4"
                               href="{% url 'blogapp:contact' %}">
                               CONTACT</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <!-- ページのヘッダーはベーステンプレートを使用するページで設定する -->
        {% block header %}{% endblock %}
        <!-- Main Content-->
        <!-- ページのコンテンツはベーステンプレートを使用するページで設定する -->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <!-- Twitterのhref属性にURLを設定 -->
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!--  Facebookのhref属性にURLを設定 -->
                                <a href="https://www.facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse">
                                        </i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <!--  GitHubのhref属性にURLを設定 -->
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <!-- 著作権の記載を独自のものに変更 -->
                        <div class="small text-center text-muted fst-italic">
                            Copyright &copy; Djang's Blog 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js">
        </script>
        <!-- Core theme JS-->
        <!-- staticでjs/scripts.jsのURLを生成する -->
        <script src={% static 'js/scripts.js' %}>
        </script>
    </body>
</html>

Django4ハンドブックsample/sample/chap06/blogproject/blogapp/templates/dailylife_list.html
<!-- <!DOCTYPE html> <html lang="ja">を削除-->
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Django's Blog - Dailylife{% endblock %}
        
        <!-- Page Header-->
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% block header %}
        <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグで設定-->
        <header class="masthead"
                style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <!-- ヘッダーの大見出し(タイトル)を設定-->
                            <h1>Django's Blog</h1>
                            <!-- サブタイトルを変更 -->
                            <span class="subheading">
                                Dailylifeカテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Main Content-->
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!--
                    レコードが格納されたdailylife_recordsから
                    レコードを1行ずつrecordに取り出す
                    -->
                    {% for record in dailylife_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <!--
                        urlでURLパターン'blog-detail/<int:pk>/'を生成し、
                        詳細ページへのリンクを設定
                        -->
                        <a href="{% url 'blogapp:blog_detail' record.pk %}">
                            <!-- 記事のタイトル -->
                            <h2 class="post-title">
                                <!-- titleフィールドを出力-->
                                {{record.title}}</h2>
                            <!-- 投稿記事の本文 -->
                            <h3 class="post-subtitle">
                                <!-- サブタイトルの文字サイズを14ptにする-->
                                <span style="font-size : 14pt">
                                    <!--
                                    contentフィールドを出力
                                    truncatecharsで出力する文字数を50以内に制限
                                    -->
                                    {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        <!-- 投稿日時とカテゴリ-->
                        <p class="post-meta">
                            <!-- ページの最上部にリンクする-->
                            <a href="#">Django's Blog</a>
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿／カテゴリ:
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- forによる繰り返しはここまで-->
                    {% endfor %}
                      
                    <!-- Pager-->
                    <!-- ページネーションが組み込まれたテンプレートの読み込み-->
                    {% include "pagination.html" %}
                </div>
            </div>
        </div>
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Footer-->
        <!-- <Footer>以下はベーステンプレートを適用するので末尾まで削除-->

Django4ハンドブックsample/sample/chap06/blogproject/blogapp/templates/index.html
<!-- <!DOCTYPE html> <html lang="ja">を削除-->
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}

<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Django's Blog{% endblock %}

    <!-- <head>～</head>を削除 -->
    <!-- <body>とコメントNavigatio以下の<nav>～</nav>を削除-->
        <!-- Navigation-->
        
        <!-- Page Header-->
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% block header %}
        <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグで設定-->
        <header class="masthead"
                style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <!-- ヘッダーの大見出し(タイトル)を設定-->
                            <h1>Django's Blog</h1>
                            <span class="subheading">
                                A Blog Theme by Start Bootstrap
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- <header>～</header>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Main Content-->
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!--
                    レコードが格納されたorderby_recordsから
                    レコードを1行ずつrecordに取り出す
                    -->
                    {% for record in orderby_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <!--
                        urlでURLパターン'blog-detail/<int:pk>/'を生成し、
                        詳細ページへのリンクを設定
                        -->
                        <a href="{% url 'blogapp:blog_detail' record.pk %}">
                            <!-- 記事のタイトル -->
                            <h2 class="post-title">
                                <!-- titleフィールドを出力-->
                                {{record.title}}</h2>
                            <!-- 投稿記事の本文 -->
                            <h3 class="post-subtitle">
                                <!-- サブタイトルの文字サイズを14ptにする-->
                                <span style="font-size : 14pt">
                                    <!--
                                    contentフィールドを出力
                                    truncatecharsで出力する文字数を50以内に制限
                                    -->
                                    {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        <!-- 投稿日時とカテゴリ-->
                        <p class="post-meta">
                            <!-- ページの最上部にリンクする-->
                            <a href="#">Django's Blog</a>
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿／カテゴリ:
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- forによる繰り返しはここまで-->
                    {% endfor %}
                      
                    <!-- Pager-->
                    <!-- ページネーションが組み込まれたテンプレートの読み込み-->
                    {% include "pagination.html" %}
                </div>
            </div>
        </div>
        <!-- メインコンテンツを設定する<div>～</div>をテンプレートタグで囲む-->
        {% endblock %}
        
        <!-- Footer-->
        <!-- <Footer>以下はベーステンプレートを適用するので末尾まで削除-->

Django4ハンドブックsample/sample/chap06/blogproject/blogapp/templates/post.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!--
 静的ファイルのURLを生成するstaticタグのロードは
 個々のページで行うことが必要
 -->
{% load static %}
<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Django's Blog{% endblock %}

<!--
<!DOCTYPE html>以下、<head>～</head>まで
ベーステンプレートで設定済みなので削除
-->

    <!-- <body>と<nav>～</nav>はベーステンプレートで設定済みなので削除 -->
        <!-- Navigation-->
        
        <!-- Page Header-->
        <!--
        ページのヘッダーはベーステンプレートを使用するページで設定するので
        テンプレートタグで囲む
         -->
        {% block header %}
        <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグに書き換え-->
        <header class="masthead"
                style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <!--
                            投稿記事のタイトル
                            <h1>タグの要素を書き換える
                            レコードをobjectで参照し、titleフィールドの値を出力
                            -->
                            <h1>{{object.title}}</h1>
                            <!--
                            サブタイトル
                            <h2>タグの要素を書き換える
                            レコードをobjectで参照し、
                            contentフィールドの値を30文字以内で出力
                            -->
                            <h2 class="subheading">
                                {{object.content|truncatechars:30}}</h2>
                            <span class="meta">
                                <!-- 投稿日時とカテゴリ -->
                                <!-- トップページにリンクする -->
                                <a href={% url 'blogapp:index' %}>
                                    Django's Blog</a>
                                <!-- 投稿日時としてposted_atフィールドを出力-->
                                {{object.posted_at}}に投稿／カテゴリ:
                                <!-- categoryフィールドを出力-->
                                {{object.category}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- ページのヘッダーに適用するテンプレートタグの終了-->
        {% endblock %}

        <!-- Post Content-->
        <!--
        <article>～</article>はベーステンプレートを
        使用するページで設定するのでテンプレートタグで囲む-->
        {% block contents %}
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <!--
                        以下<div>タグの要素を書き換える
                        レコードをobjectで参照し、contentフィールドの値を出力
                        <p>～</p>の要素とすることで全体を1つの段落にする -->
                        <p>{{object.content}}</p>
                    </div>
                </div>
            </div>
        </article>
        <!-- 水平線を追加-->
        <hr>
        <!-- テンプレートタグの終了-->
        {% endblock %}
        
        <!-- Footer-->
        <!-- <footer>以下はベーステンプレートで設定するので削除-->